/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * BADL Capability Definition
 */
export type Capability = Capability1 & Capability2;
export type Capability1 = {
  [k: string]: unknown;
};

/**
 * BADL Domain Definition
 */
export interface Domain {
  id: string;
  name: string;
  version: string;
  domain: string;
  entities: Entity[];
  capabilities?: Capability[];
  contracts?: Contract[];
}
/**
 * BADL Entity Definition
 */
export interface Entity {
  id: string;
  name: string;
  implements?: string[];
  fields: {
    id: string;
    name: string;
    type: 'string' | 'boolean' | 'date' | 'number' | 'array' | 'object';
    itemType?: string;
    label: string;
    references?: string;
    validation: string[];
    metadata_path: string;
  }[];
}
export interface Capability2 {
  id: string;
  /**
   * Strict vocabulary of core capability verbs
   */
  name: 'Create' | 'Read' | 'Update' | 'Delete' | 'List';
  description: string;
  type: 'Command' | 'Query';
  /**
   * Target entity for this capability
   */
  entityId: string;
  outcome_ref: string[];
  preconditions: string[];
  postconditions: string[];
  permissions: string[];
  risk_level: 'low' | 'medium' | 'high' | 'critical';
  interaction_contract_ref?: string;
  async: boolean;
}
/**
 * BADL Contract Definition
 */
export interface Contract {
  id: string;
  name: string;
  requiredFields: {
    name: string;
    type: 'string' | 'boolean' | 'date' | 'number' | 'array' | 'object';
  }[];
  requiredCapabilities: {
    name: string;
    type: 'Command' | 'Query';
  }[];
}
