/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * BADL Domain Definition
 */
export interface Domain {
  id: string;
  name: string;
  version: string;
  domain: string;
  entities: Entity[];
  capabilities?: {
    id: string;
    name: string;
    type: string;
    entityId: string;
  }[];
}
/**
 * BADL Entity Definition
 */
export interface Entity {
  id: string;
  name: string;
  fields: {
    id: string;
    name: string;
    type: 'string' | 'boolean' | 'date' | 'number' | 'array' | 'object';
    itemType?: string;
    label: string;
    references?: string;
    validation: string[];
    metadata_path: string;
  }[];
}
